services:
  web-client:
    build:
        context: ./.
        dockerfile: Dockerfile
    container_name: scraper-client1
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api/v1/
